<DartScreen>
    BoxLayout:
        orientation: 'vertical'
        # size_hint: 0.9, 0.9
        Image:
            id: tile_image
            source: 'penrose_dart.png'
        Button:
            id: change_tile
            text: 'Change Tile'
            size_hint: None, None
            pos_hint: {'center_x': 0.5}
            on_press: root.change_source()
            # text_size: cm(2), cm(2)
